2018-09-04 11:04:09 [scrapy.core.scraper] ERROR: Error downloading <GET https://www.booking.com/searchresults.ru.html?id=test&ss=%D0%97%D0%B0%D0%BF%D0%BE%D1%80%D0%BE%D0%B6%D1%8C%D0%B5+%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D0%B0&checkin_monthday=12&checkin_month=12&checkin_year=2018&checkout_monthday=13&checkout_month=12&checkout_year=2018>
Traceback (most recent call last):
  File "C:\Users\kulik_li\.virtualenvs\scraping-management-SOykYk2W\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy pl35.nordvpn.com:80 [{'status': 407, 'reason': b'Proxy Authentication Required'}]
2018-09-04 11:04:09 [booking] Level 45: {'start_time': datetime.datetime(2018, 9, 4, 8, 4, 2, 724637), 'scheduler/enqueued/memory': 3, 'scheduler/enqueued': 3, 'scheduler/dequeued/memory': 3, 'scheduler/dequeued': 3, 'downloader/request_count': 3, 'downloader/request_method_count/GET': 3, 'downloader/request_bytes': 2241, 'downloader/exception_count': 3, 'downloader/exception_type_count/scrapy.core.downloader.handlers.http11.TunnelError': 3, 'retry/count': 2, 'retry/reason_count/scrapy.core.downloader.handlers.http11.TunnelError': 2, 'retry/max_reached': 1, 'log_count/ERROR': 1, 'log_count/Level 45': 1}
2018-09-04 11:04:11 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
  File "C:\Users\kulik_li\.virtualenvs\scraping-management-SOykYk2W\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Users\kulik_li\.virtualenvs\scraping-management-SOykYk2W\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Users\kulik_li\.virtualenvs\scraping-management-SOykYk2W\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Users\kulik_li\.virtualenvs\scraping-management-SOykYk2W\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "C:\Users\kulik_li\.virtualenvs\scraping-management-SOykYk2W\lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "C:\Users\kulik_li\.virtualenvs\scraping-management-SOykYk2W\lib\site-packages\twisted\internet\tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "C:\Users\kulik_li\.virtualenvs\scraping-management-SOykYk2W\lib\site-packages\twisted\internet\tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "C:\Users\kulik_li\.virtualenvs\scraping-management-SOykYk2W\lib\site-packages\twisted\protocols\tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "C:\Users\kulik_li\.virtualenvs\scraping-management-SOykYk2W\lib\site-packages\twisted\protocols\tls.py", line 300, in _flushReceiveBIO
    self._flushSendBIO()
  File "C:\Users\kulik_li\.virtualenvs\scraping-management-SOykYk2W\lib\site-packages\twisted\protocols\tls.py", line 252, in _flushSendBIO
    bytes = self._tlsConnection.bio_read(2 ** 15)
builtins.AttributeError: 'NoneType' object has no attribute 'bio_read'

2018-09-04 11:09:46 [booking] Level 45: {'start_time': datetime.datetime(2018, 9, 4, 8, 8, 51, 402612), 'scheduler/enqueued/memory': 113, 'scheduler/enqueued': 113, 'scheduler/dequeued/memory': 113, 'scheduler/dequeued': 113, 'downloader/request_count': 335, 'downloader/request_method_count/GET': 335, 'downloader/request_bytes': 281203, 'downloader/response_count': 335, 'downloader/response_status_count/200': 335, 'downloader/response_bytes': 36742516, 'response_received_count': 335, 'request_depth_max': 9, 'file_count': 222, 'file_status_count/downloaded': 222, 'item_scraped_count': 104, 'log_count/Level 45': 1}
2018-09-04 11:09:48 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
  File "C:\Users\kulik_li\.virtualenvs\scraping-management-SOykYk2W\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Users\kulik_li\.virtualenvs\scraping-management-SOykYk2W\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Users\kulik_li\.virtualenvs\scraping-management-SOykYk2W\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Users\kulik_li\.virtualenvs\scraping-management-SOykYk2W\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "C:\Users\kulik_li\.virtualenvs\scraping-management-SOykYk2W\lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "C:\Users\kulik_li\.virtualenvs\scraping-management-SOykYk2W\lib\site-packages\twisted\internet\tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "C:\Users\kulik_li\.virtualenvs\scraping-management-SOykYk2W\lib\site-packages\twisted\internet\tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "C:\Users\kulik_li\.virtualenvs\scraping-management-SOykYk2W\lib\site-packages\twisted\protocols\tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "C:\Users\kulik_li\.virtualenvs\scraping-management-SOykYk2W\lib\site-packages\twisted\protocols\tls.py", line 300, in _flushReceiveBIO
    self._flushSendBIO()
  File "C:\Users\kulik_li\.virtualenvs\scraping-management-SOykYk2W\lib\site-packages\twisted\protocols\tls.py", line 252, in _flushSendBIO
    bytes = self._tlsConnection.bio_read(2 ** 15)
builtins.AttributeError: 'NoneType' object has no attribute 'bio_read'

